# some config and ref is combined from udemy course and https://www.elastic.co/blog/getting-started-with-the-elastic-stack-and-docker-compose

version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.1
    ports:
      - 5044:5044
    volumes:
      - ./logstashconfig/pipeline:/usr/share/logstash/pipeline
      - ./exercises/s04/access_log:/home/access_log
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_HOSTS=http://elasticsearch:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibanadata:/usr/share/kibana/data

  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./exercises/s04/ml-100k:/home/ml-100k
volumes:
  esdata:
