version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibanadata:/usr/share/kibana/data

volumes:
  esdata:
